### ISSUE TITLE
linters depfu PRs always need extra work

### ISSUE THREAD

**Issue by Ana06** [depfu/feedback#15]
When depfu updates linters like rubocop or haml-lint, it is normally the case that the tests fail. :sob: It would be great if there was a way to tell depfu that for some gems it should also run an specific task. I think it is not possible to achieve something like that at the moment. This would completely automatise the process of updating this gems and for sure save many people a lot of time. :wink:

**Comment by theflow** [comment]
Yeah, I've just heard a similar request recently.

The problem for us is that we don't want to become a CI service :) And we would need to in order to run a script on your code. We could send a webhook, but not sure how you would integrate that, so I don't think it's a good solution.

What are you using for CI? One way to maybe solve it would be to configure your CI to run that script based on the branch name (which are very specific for Depfu updates).

**Comment by Ana06** [comment]
@theflow 

> What are you using for CI? One way to maybe solve it would be to configure your CI to run that script based on the branch name (which are very specific for Depfu updates).

That may be one solution. Actually probably the only one if you don't want depfu to become a CI service. Then I'll close the issue. Thanks for your answer :wink:
