### ISSUE TITLE
When depfu create PR?

### ISSUE THREAD

**Issue by ryota-murakami** [depfu/feedback#17]
Hey, I'm RyotaMurakami😀
I'm using Depfu CreateReactApp project and like it!
that infomation(changelog, commit log) is useful written by PR.

# Question
> I wrote at `Fri Jul 20 2018 08:46:37 GMT+0900 (Japan Standard Time)` 

I have a OSS React Application. https://github.com/ryota-murakami/clock-up
Today i was run `yarn outdated` command, result is following.

<img width="989" alt="screen shot 2018-07-20 at 8 36 39" src="https://user-images.githubusercontent.com/5501268/42976288-c092b95e-8bfb-11e8-8a78-bbba1481efa0.png">

6 package are update available.
But Depfu didn't create PR.

![screen shot 2018-07-20 at 9 04 54](https://user-images.githubusercontent.com/5501268/42976349-1045126c-8bfc-11e8-9912-67bd87afaf23.png)

Conclusion, my question is When Depfu create PR?

thnak you made awesome tool😀🎉

**Comment by theflow** [comment]
Hi RyotaMurakami,

hmm, are you sure you're on the updated master branch when you ran this? I'm getting this on ryota-murakami/clock-up:

```
~/tmp/clock-up git:(master) ▶ yarn outdated
yarn outdated v1.5.1
info Color legend : 
 "<red>"    : Major Update backward-incompatible updates 
 "<yellow>" : Minor Update backward-compatible features 
 "<green>"  : Patch Update backward-compatible bug fixes
Package               Current Wanted Latest Package Type    URL                                                       
react-testing-library 4.1.2   4.1.3  4.1.3  devDependencies https://github.com/kentcdodds/react-testing-library#readme
✨  Done in 0.79s.
```

which is the same as the Depfu dashboard shows, where only "react-testing-library" is outdated. But since you've specified a version requirement, by default we [don't send you PR for those](https://depfu.com/blog/2017/08/16/how-depfu-handles-version-constraints). You can enable it as a setting if you want to get PRs for those.

**Comment by ryota-murakami** [comment]
@theflow Uhhh I'm stupid, my local master branch was older than Depfu PR merged origin master😅

Thank you for sharing blog, and polite support🙇‍♂️
