### ISSUE TITLE
Pull request with changed git source URLs of other dependencies

### ISSUE THREAD

**Issue by nning** [depfu/feedback#2]
Hey,

thanks for this service!

I registered a repository for a test run and got the first PR but not only the version of the mentioned dependency is changed. The schema part in two URLs of other dependencies was also changed (from https to git) and this causes the tests to fail.

https://github.com/nning/imgshr/pull/2/files

Thanks again and best regards,
henning

**Comment by theflow** [comment]
Thanks for reporting this, @nning!

It looks like you configured your Bundler to use https locally? Because usually `github:` resolves into a `git://` URL. Maybe like this:

```
bundle config github.https true
```

While we should be a bit smarter to never rewrite the URLs, it's actually quite hard for us to figure out since we don't know about your local bundle config (and neither would other developers on this project). I think it would be more reliable for you to switch all the `github:` gems to use `git:` instead like this

```
gem 'best_in_place', git: 'https://github.com/luckie/best_in_place', branch: 'multi-select'
```

Which is also the [recommendation from Bundler](http://bundler.io/v1.15/guides/git.html#security).

**Comment by nning** [comment]
Oh, thank you very much for your answer! It is clearly a bad idea to only define the GitHub https source locally. I fixed it like in rails:

https://github.com/rails/rails/blob/master/Gemfile#L5

Thanks for your help!
