### ISSUE TITLE
Language Support - Rust, Java, Kotlin?

### ISSUE THREAD

**Issue by rpsrosario** [depfu/feedback#27]
Depfu seems to be very interesting, however it works only with languages that I (personally) don't use, hence my question: Is there any planned support for languages like Rust, Java or Kotlin?

In the Rust ecosystem you have the [cargo][1] package manager that uses a `Cargo.toml`and a `Cargo.lock`file for dependency management.

In the Java/Kotlin ecosystem there are several tools, but I believe one of the most common is [Gradle][2], although in this case the build process doesn't necessarily have a fixed structure.

Even if not these languages specifically I think it would be interesting for users to have an idea of which languages are planned to be supported, or maybe to allow for the community to contribute language support in some way.

[1]: https://doc.rust-lang.org/cargo/
[2]: https://gradle.org/

**Comment by halfbyte** [comment]
@rpsrosario Thanks for that feedback. We're always interested to hear what other languages would be interesting for people, so I'll count these as votes for Gradle and Cargo. :)

The reason we haven't talked about plans to support other languages is because we haven't made any decisions yet, as we're still trying to figure out what would make the most sense for us.

**Comment by rpsrosario** [comment]
@halfbyte Thank you for your answer :)

You mentioned that you'll count these as votes for Gradle and Cargo, is there someplace where people can check which languages / frameworks are being requested the most?

**Comment by theflow** [comment]
Closing this in favor of a more general issue: https://github.com/depfu/feedback/issues/38
