### ISSUE TITLE
I miss badges.  Can we have badges?

### ISSUE THREAD

**Issue by autobolt** [depfu/feedback#3]
Are there badges already?  If so, can we have your badges integrated with [shields.io](http://shields.io)?

**Comment by pboling** [comment]
I meant to post this as myself, not a machine user.  #RiseOfTheMachines.

**Comment by mindlace** [comment]
ok, here are some badgers:

https://www.youtube.com/watch?v=NL6CDFn2i3I

**Comment by leoarnold** [comment]
Since Depfu does not show up among the contributers to the repository (on GitHub that is) it would be nice to show off (i.e. free advertisement for Depfu, hint-hint) with a badge. Maybe one that counts the number of Depfu PRs merged.

Also, [GitLab aquired Gemnasium](https://techcrunch.com/2018/01/30/gitlab-acquires-gemnasium-to-strengthen-its-security-services/), so GitHubbers might be on the lookout for a working alternative (i.e. Depfu) soon.

**Comment by pboling** [comment]
@theflow What say you?

**Comment by theflow** [comment]
I can make something happen :)

Just never a big fan of the Gemnasium badge, since it would should as "Outdated" pretty much all the time.

**Comment by pboling** [comment]
Agreed.  The metric of the badge should be carefully considered.  Some ideas, of which a badge could integrate one or more:

* Average age of open Depfu PRs in days, months, or years
* Average age between open and close of Depfu PRs in days, months, or years
* Number of Depfu PRs merged (@leoarnold 's idea)
* Number of open Depfu PRs (not merged)

**Comment by leoarnold** [comment]
"Number of open Depfu PRs (not merged)" could come off as shaming the maintainers.

**Comment by pboling** [comment]
Shaming, sure, but perhaps also motivating?  The goal as I see it would be to spur community involvement among those who depend on a project, by alerting people to the state of the project.  It will also help people who are not yet depending on a project to be able to make a more informed decision about whether or not to adopt / invest in a project.

**Comment by theflow** [comment]
Ok, I've implemented a few prototypes:

![badges](https://user-images.githubusercontent.com/1552/36110062-ad6fc944-1021-11e8-8585-54e230842b46.png)

### Overview Badge

Pretty straightforward and similar to what's already out there: shows `up-to-date`, `outdated`, `insecure` for runtime dependencies. I was thinking about making the outdated less harsh by

 * ignoring patch releases (so it only counts as outdated if you're at least a minor version behind)
 * and/or allowing a certain amount (25%) of dependencies to be outdated

I think it doesn't really matter that a few are outdated, because as a user I want the library to just care about updating from time-to-time.

### Count Badge

I like the simplicity of this one. Same rule ignoring patch releases as above. I also like that it immediately gives you an idea how many dependencies this library uses.

### Depfu

This is very Depfu specific and doesn't really tell a user much about the state of dependencies. But maybe more of a "I'm using Depfu" badge?

Let me know what you folks think!

**Comment by pboling** [comment]
I am very much in love with the count badge. ☑️

**Comment by leoarnold** [comment]
The prototype of the "Depfu" badge is way longer than the usual badges and therefore a little odd. And the "Overview" badge is indistinguishable from the Gemnasium badge to me.

**Comment by pboling** [comment]
To shorten, all of the badges could use `Depfu` on the left side instead of `dependencies`.

**Comment by theflow** [comment]
This is done: https://depfu.com/blog/rethinking-the-dependencies-badge
